config/routes.rb
Rails.application.routes.draw do
  resources :helps
  resources :member_points
  resources :activities
  resources :posts
  resources :bios

  resources :likes do
    member do
      get :delete
    end
  end

  resources :logins
  # root to: 'dashboards#show'
  # will automatically redirect users to the sign in page upon entering the website
  root to: 'announcements#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # temporarily set the announcements page as home, for convenience
  # the google oauth tutorial had me set a different root idk how were going to do this

  resources :meetings do
    resources :joins
  end

  resources :events

  resources :joins

  get 'member/ManageMembers'

  resources :announcements do
    member do
      get :delete
    end
  end

  resources :members do
    resources :bios
  end

  resources :helps, :path => 'help'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :member_points, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
  validates :member_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :member_points, dependent: :destroy
end

app/models/help.rb
class Help < ApplicationRecord
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :meeting
end

app/models/like.rb
class Like < ApplicationRecord
  validates :member_id, presence: true
  validates :post_id, presence: true

  def delete
    @like = Like.find(params[:id])
    @post = Post.find(params[:post_id])
    @post_id = params[:post_id]
    @like.destroy
    @post_likes = Like.where(post_id: @post_id).pluck('DISTINCT member_id').count
    Post.update(@post_id, likes: @post_likes)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'You have un-liked this post.' }
      format.json { head :no_content }
    end
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :joins

  accepts_nested_attributes_for :joins
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :member_points, dependent: :destroy
  has_one :bio, dependent: :destroy
end

app/models/member_point.rb
class MemberPoint < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[show edit update destroy]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show; end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit; end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.save

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:status, :name, :date)
  end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def sortable(collumn, title = nil)
    title ||= collumn.titleize
    direction = collumn == params[:sort] && params[:direction] == 'ASC' ? 'DESC' : 'ASC'
    link_to title, sort: collumn, direction: direction
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |meeting_form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being joined:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= meeting_form.label :status %>
    <%= meeting_form.check_box :status %>
  </div>
  <div class="field">
    <%= meeting_form.label :name %>
    <%= meeting_form.text_field :name %>
  </div>
  <div class="field">
    <%= meeting_form.label :date %>
    <%= meeting_form.date_select :date %>
  </div>

  <div class="actions">
    <%= meeting_form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>

    <h1>Editing Meeting</h1>

    <%= render 'form', meeting: @meeting %>

    <%= link_to 'Show', @meeting %> |
    <%= link_to 'Back', meetings_path %>

  </div>
</div>

app/views/meetings/index.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>

    <p id="notice"><%= notice %></p>

    <h1>Meetings</h1>
    <%= link_to("To Home Page", {:controller => 'announcements', :action=>'index'}, :class => 'underline')%>

    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Name</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @meetings.each do |meeting| %>
          <tr>
            <td><%= meeting.status %></td>
            <td><%= meeting.name %></td>
            <td><%= meeting.date %></td>
            <td><%= link_to 'Show', meeting %></td>
            <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
            <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Meeting', new_meeting_path, :class => 'underline' %>

  </div>
</div>

app/views/meetings/new.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>

    <h1>New Meeting</h1>

    <%= render 'form', meeting: @meeting %>

    <%= link_to 'Back', meetings_path, :class => 'underline' %>

  </div>
</div>

app/views/meetings/show.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>

    <p id="notice"><%= notice %></p>

    <p>
      <strong>Status:</strong>
      <%= @meeting.status %>
    </p>
    <p>
      <strong>Name:</strong>
      <%= @meeting.name %>
    </p>
    <p>
      <strong>Date:</strong>
      <%= @meeting.date %>
    </p>

    <%= link_to 'Edit', edit_meeting_path(@meeting), :class => 'underline' %> |
    <%= link_to 'Back', meetings_path, :class => 'underline' %>

    <%= link_to("Join Meeting", new_join_path(:meeting_id => @meeting.id, :member_id => 1), :class => 'underline')%>

  </div>
</div>