config/routes.rb
Rails.application.routes.draw do
  resources :helps
  resources :member_points
  resources :activities
  resources :posts
  resources :bios

  resources :likes do
    member do
      get :delete
    end
  end

  resources :logins
  # root to: 'dashboards#show'
  # will automatically redirect users to the sign in page upon entering the website
  root to: 'announcements#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # temporarily set the announcements page as home, for convenience
  # the google oauth tutorial had me set a different root idk how were going to do this

  resources :meetings do
    resources :joins
  end

  resources :events

  resources :joins

  get 'member/ManageMembers'

  resources :announcements do
    member do
      get :delete
    end
  end

  resources :members do
    resources :bios
  end

  resources :helps, :path => 'help'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :member_points, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
  validates :member_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :member_points, dependent: :destroy
end

app/models/help.rb
class Help < ApplicationRecord
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :meeting
end

app/models/like.rb
class Like < ApplicationRecord
  validates :member_id, presence: true
  validates :post_id, presence: true

  def delete
    @like = Like.find(params[:id])
    @post = Post.find(params[:post_id])
    @post_id = params[:post_id]
    @like.destroy
    @post_likes = Like.where(post_id: @post_id).pluck('DISTINCT member_id').count
    Post.update(@post_id, likes: @post_likes)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'You have un-liked this post.' }
      format.json { head :no_content }
    end
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :joins

  accepts_nested_attributes_for :joins
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :member_points, dependent: :destroy
  has_one :bio, dependent: :destroy
end

app/models/member_point.rb
class MemberPoint < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @current_member = Member.where(uid: current_admin.uid).first

    @is_admin = @current_member.isAdmin

    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.save

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:status, :name, :date, :activity_id)
  end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def sortable(collumn, title = nil)
    title ||= collumn.titleize
    direction = collumn == params[:sort] && params[:direction] == 'ASC' ? 'DESC' : 'ASC'
    link_to title, sort: collumn, direction: direction
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :status, "Active" %>
    <%= form.check_box :status %>
  </div>

  <div class="field">
    <%= form.label :activity %>
    <%= form.select :activity_id, Activity.all.collect {|x| [x.name, x.id]}, {}, {class: "multiple", style: 'color: black;'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_navbar.html.erb
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>

  <div class="nav-links">
    <a href="/">Home</a>
    <a href="/announcements">Announcements</a>
    <a href="/members">Members</a>
    <a href="/events">Events</a>
    <a href="/posts">Posts</a>
    <a href="/help">Need Help?</a>
    <% if @is_admin %>
      <a href="/activities">Activities</a>
    <% end %>
    <% if is_logged_in %>
    <%= link_to "Sign Out", destroy_admin_session_path %>
    <% else %>
    <%= link_to "Sign In", admin_google_oauth2_omniauth_authorize_path %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
        <h1>Editing Event</h1>

        <%= render 'form', event: @event %>

        <%= link_to 'Show', @event %> |
        <%= link_to 'Back', events_path %>  

    </div>
</div>

app/views/events/index.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
    <p id="notice"><%= notice %></p>

    <h1>Events</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Active</th>
          <th>Activity Type</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date %></td>
            <% if event.status == true %>
              <td> Yes </td>
            <% else %>
              <td> No </td>
            <% end %>
            <% @activity = Activity.find(event.activity_id) %>
            <td><%= @activity.name %></td>
            <% @member_id = Member.where(uid: current_admin.uid).first().id %>
            <% if (MemberPoint.exists?(:member_id => @member_id, :event_id => event.id) == false && event.status == true) %>
              <td><%= link_to("Join this event", member_points_path(:member_point => @memberpoint, :event_id => event.id, :member_id => @member_id, :activity_id => event.activity_id, :points => @activity.num_points, :date => event.date), method: :create) %>
            <% end %></td>
            <td><%= link_to 'Show', event, :class => 'underline' %></td>
            <% if @is_admin %>
            <td><%= link_to 'Edit', edit_event_path(event), :class => 'underline' %></td>
            <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'underline' %></td>
            <% end %>
            <br>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <% if @is_admin %>
    <%= link_to 'New Event', new_event_path, :class => 'underline' %>
    <% end %>

  </div>
</div>

app/views/events/new.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
        <h1>New Event</h1>

        <%= render 'form', event: @event %>

        <%= link_to 'Back', events_path %>
    </div>
</div>

app/views/events/show.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Active:</strong>
        <% if @event.status == true %>
          <td> Yes </td>
        <% else %>
          <td> No </td>
        <% end %>
    </p>

    <p>
      <strong>Activity Type:</strong>
      <% @activity = Activity.find(@event.activity_id) %>
      <%= @activity.name %>
    </p>

    <p>
      <strong>Attendance: </strong>
      <% if MemberPoint.exists?(:event_id => @event.id) == true %>
        <%= MemberPoint.where(event_id: @event.id).pluck('DISTINCT member_id').count %>
      <% else %>
        0
      <% end %>

    </p>

    <p>
      <strong>Attendees:</strong>
      <% if MemberPoint.exists?(:event_id => @event.id) == true %>
        <% @memberpoints = MemberPoint.where(:event_id => @event.id) %>
        <% @memberpoints.each do |memberpoint| %>
          <% @member = Member.find(memberpoint.member_id) %>
          <%= @member.name %>
          <br>
        <% end %>
      <% end %>
    </p>
    

    <% @member_id = Member.where(uid: current_admin.uid).first().id %>

    <% if (MemberPoint.exists?(:member_id => @member_id, :event_id => @event.id) == false && @event.status == true) %>

      <%= link_to("Join this event", member_points_path(:member_point => @memberpoint, :event_id => @event.id, :member_id => @member_id, :activity_id => @event.activity_id, :points => @activity.num_points, :date => @event.date), method: :create) %> |

    <% end %>


    <% if @is_admin %>
      <%= link_to 'Edit', edit_event_path(@event) %> |
    <% end %>
    <%= link_to 'Back', events_path %>

  </div>
</div>