config/routes.rb
Rails.application.routes.draw do
  resources :helps
  resources :member_points
  resources :activities
  resources :posts
  resources :bios

  resources :likes do
    member do
      get :delete
    end
  end

  resources :logins
  # root to: 'dashboards#show'
  # will automatically redirect users to the sign in page upon entering the website
  root to: 'announcements#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # temporarily set the announcements page as home, for convenience
  # the google oauth tutorial had me set a different root idk how were going to do this

  resources :meetings do
    resources :joins
  end

  resources :events

  resources :joins

  get 'member/ManageMembers'

  resources :announcements do
    member do
      get :delete
    end
  end

  resources :members do
    resources :bios
  end

  resources :helps, :path => 'help'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :member_points, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
  validates :member_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :member_points, dependent: :destroy
end

app/models/help.rb
class Help < ApplicationRecord
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :meeting
end

app/models/like.rb
class Like < ApplicationRecord
  validates :member_id, presence: true
  validates :post_id, presence: true

  def delete
    @like = Like.find(params[:id])
    @post = Post.find(params[:post_id])
    @post_id = params[:post_id]
    @like.destroy
    @post_likes = Like.where(post_id: @post_id).pluck('DISTINCT member_id').count
    Post.update(@post_id, likes: @post_likes)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'You have un-liked this post.' }
      format.json { head :no_content }
    end
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :joins

  accepts_nested_attributes_for :joins
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :member_points, dependent: :destroy
  has_one :bio, dependent: :destroy
end

app/models/member_point.rb
class MemberPoint < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :set_help, only: %i[ show edit update destroy ]

  # GET /helps or /helps.json
  def index
    @helps = Help.all
  end

  # GET /helps/1 or /helps/1.json
  def show
  end

  # GET /helps/new
  def new
    @help = Help.new
  end

  # GET /helps/1/edit
  def edit
  end

  # POST /helps or /helps.json
  def create
    @help = Help.new(help_params)

    respond_to do |format|
      if @help.save
        format.html { redirect_to @help, notice: "Help was successfully created." }
        format.json { render :show, status: :created, location: @help }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helps/1 or /helps/1.json
  def update
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: "Help was successfully updated." }
        format.json { render :show, status: :ok, location: @help }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @help.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helps/1 or /helps/1.json
  def destroy
    @help.destroy
    respond_to do |format|
      format.html { redirect_to helps_url, notice: "Help was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help
      @help = Help.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def help_params
      params.fetch(:help, {})
    end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def sortable(collumn, title = nil)
    title ||= collumn.titleize
    direction = collumn == params[:sort] && params[:direction] == 'ASC' ? 'DESC' : 'ASC'
    link_to title, sort: collumn, direction: direction
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/helps/_form.html.erb
<%= form_with(model: help) do |form| %>
  <% if help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
        <% help.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/helps/_navbar.html.erb
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>

  <div class="nav-links">
    <a href="/">Home</a>
    <a href="/announcements">Announcements</a>
    <a href="/members">Members</a>
    <a href="/events">Events</a>
    <a href="/posts">Posts</a>
    <a href="/help">Need Help?</a>
    <% if @is_admin %>
      <a href="/activities">Activities</a>
    <% end %>
    <% if is_logged_in %>
    <%= link_to "Sign Out", destroy_admin_session_path %>
    <% else %>
    <%= link_to "Sign In", admin_google_oauth2_omniauth_authorize_path %>
    <% end %>
  </div>
</div>

app/views/helps/edit.html.erb
<h1>Editing Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

app/views/helps/index.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
    <h1>Help Page</h1>
    <br>

    <% @member = Member.where(uid: current_admin.uid).first() %>
    <% if @member.isAdmin %>
      <h2>Guide for Admins</h2>
      <h3>This Portion is Only Visible to Admins</h3><br>

      <h2>Announcements Page</h2>
      <%= image_tag("announcements.jpg") %>
      <p>As an admin, you have the ability to post, edit, and delete announcements on this page. Any time an announcement gets posted, an email will be sent out to all members. </p> <br>

      <h2>Members Page</h2>
      <%= image_tag("members.jpg") %>
      <p>Admins have the ability to edit and delete any member within the organization. </p>
      <%= image_tag("member_edit.jpg") %>
      <p>This is the form to edit members as an admin. You can make adjustments to the user's display name and attendance points if needed. Note: Only the site owner can make changes to admin privileges. </p><br>

      <h2>Creating Events</h2>
      <p>Every event that is created will need to have an activity type associated with it. Activites can be created by admins by clicking the "Activities" tab on the navigation bar. </p>
      <%= image_tag("activities.jpg") %>
      <p>To create an activity type, click "New Activity" to access the form. On the form, you will need to enter a name for the activity type as well as the amount of points awarded for attending this type of activity. </p>
      <%= image_tag("new_activity.jpg") %>
      <p>Once the activity type is created, you can navigate to the events page and create an event that members can join. If the "Active" box is checked, members will be able to join the event and gain attendance points. The "Activity" field is a dropdown box that contains all the activity types you have created.</p> <br>

      <h2>Posts Page</h2>
      <p>Admins do not have access to edit posts of other members. However, admins can delete posts they deem inappropriate. Simply click "Delete" on a post and confirm on the pop-up box.</p>
      <%= image_tag("delete_post.jpg") %> <br> <br> 

    <% end %>
    
    <h2>User Guide</h2>
    <h3>This page will be a guide on how to navigate and utilize this website.</h3> <br>

    <h2>Announcements Page</h2>
    <p>The announcement page will contain all the announcements created by the organization admins. Each time an announcement is posted, you will get an email to your @tamu.edu address that you used to sign into the website. </p>
    <%= image_tag("announcements_user.jpg") %> <br>

    <h2>Members Page</h2>
    <p>On the members page, you can view a list of all the members in your organization. This page will display attendance points and also have links to edit your profile. If you click the "Edit" link, you can adjust your display name on the website. If you click on "View Bio", you will be taken to the member's personal bio page. </p>
    <%= image_tag("members_user.jpg") %> <br>
    <p>The bio page will display the respective member's information including a personal bio that they can write. If you are on your own member page, there will be links to add a bio or edit your existing bio. Each personal member page will also display every posts created by that user. </p>
    <%= image_tag("bio.jpg") %> <br>
    <p>Clicking on "View Points History" will display a list of the events the member attended and how many points they got awarded for attending.</p> <br>


    <h2>Events Page</h2>
    <p>In order to gain attendance points, you wil need to join events that are active. Navigate to the events page to view all the events for your organization. If an event is set to active, you will see a link to "Join this event". </p>
    <%= image_tag("events_user.jpg") %> <br>
    <p>Once you join an event, you will be added to the attendee list and be awarded attendance points.</p>
    <%= image_tag("join_event.jpg") %> <br>

    
    <h2>Posts Page</h2>
    <p>The posts page will be where you can interact with your fellow members and see their accomplishments. There will be an option to like/un-like every post as well. If needed, you can edit your own posts if you need to change something. </p>
    <%= image_tag("posts.jpg") %> <br>


    <br>

  </div>
</div>

app/views/helps/new.html.erb
<h1>New Help</h1>

<%= render 'form', help: @help %>

<%= link_to 'Back', helps_path %>

app/views/helps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_help_path(@help) %> |
<%= link_to 'Back', helps_path %>