config/routes.rb
Rails.application.routes.draw do
  resources :helps
  resources :member_points
  resources :activities
  resources :posts
  resources :bios

  resources :likes do
    member do
      get :delete
    end
  end

  resources :logins
  # root to: 'dashboards#show'
  # will automatically redirect users to the sign in page upon entering the website
  root to: 'announcements#index'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # temporarily set the announcements page as home, for convenience
  # the google oauth tutorial had me set a different root idk how were going to do this

  resources :meetings do
    resources :joins
  end

  resources :events

  resources :joins

  get 'member/ManageMembers'

  resources :announcements do
    member do
      get :delete
    end
  end

  resources :members do
    resources :bios
  end

  resources :helps, :path => 'help'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :member_points, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
  validates :member_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :member_points, dependent: :destroy
end

app/models/help.rb
class Help < ApplicationRecord
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :meeting
end

app/models/like.rb
class Like < ApplicationRecord
  validates :member_id, presence: true
  validates :post_id, presence: true

  def delete
    @like = Like.find(params[:id])
    @post = Post.find(params[:post_id])
    @post_id = params[:post_id]
    @like.destroy
    @post_likes = Like.where(post_id: @post_id).pluck('DISTINCT member_id').count
    Post.update(@post_id, likes: @post_likes)
    respond_to do |format|
      format.html { redirect_to @post, notice: 'You have un-liked this post.' }
      format.json { head :no_content }
    end
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :joins

  accepts_nested_attributes_for :joins
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :member_points, dependent: :destroy
  has_one :bio, dependent: :destroy
end

app/models/member_point.rb
class MemberPoint < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    if Member.exists?(uid: current_admin.uid) == false
      redirect_to(new_member_path)
    else
      @current_member = Member.where(uid: current_admin.uid).first
      @is_admin = @current_member.isAdmin
    end

    @posts = Post.order('created_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    unless verify
      redirect_to(posts_url, notice: 'Post must have title and body.')
      return
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def verify
    (!@post.title.empty? and !@post.body.empty?)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :member_id)
  end
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def sortable(collumn, title = nil)
    title ||= collumn.titleize
    direction = collumn == params[:sort] && params[:direction] == 'ASC' ? 'DESC' : 'ASC'
    link_to title, sort: collumn, direction: direction
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <% @member_id = Member.where(uid: current_admin.uid).first() %>
  <%= form.hidden_field :member_id, :value => @member_id.id %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_navbar.html.erb
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>

  <div class="nav-links">
    <a href="/">Home</a>
    <a href="/announcements">Announcements</a>
    <a href="/members">Members</a>
    <a href="/events">Events</a>
    <a href="/posts">Posts</a>
    <a href="/help">Need Help?</a>
    <% if @is_admin %>
      <a href="/activities">Activities</a>
    <% end %>
    <% if is_logged_in %>
    <%= link_to "Sign Out", destroy_admin_session_path %>
    <% else %>
    <%= link_to "Sign In", admin_google_oauth2_omniauth_authorize_path %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
        <h1>Editing Post</h1>

        <%= render 'form', post: @post %>

        <%= link_to 'Show', @post, :class => 'underline' %> |
        <%= link_to 'Back', posts_path, :class => 'underline' %>
    </div>
</div>

app/views/posts/index.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
    <p id="notice"><%= notice %></p>
    <h1>Posts</h1>

    <%= link_to 'New Post', new_post_path, :class => 'underline' %>
    <br><br>
    <% @posts.each do |post| %>
      <div class='box'>
        <b><%= post.title %></b>
        <% @user = Member.find(post.member_id) %>
        <p>By <%= @user.name %></p>
        <p><%= post.body %></p>
        <br>
        <p style="display:inline">Likes: <%= post.numlikes %></p><br>
        <% @member_id = Member.where(uid: current_admin.uid).first().id %>

        <% if(Like.exists?(:member_id => @member_id, :post_id => post.id)) %>
          <% @like = Like.find_by(member_id: @member_id, post_id: post.id) %>
          <%= link_to("Un-like", delete_like_path(@like, :post_id => post.id, :member_id => @member_id), :class => 'underline') %>
        <% else %>

          <%= link_to("Like", likes_path(:like => @like, :post_id => post.id, :member_id => @member_id), method: :create, :class => 'underline') %>
        <% end %>

        <% if @member_id == post.member_id %>
          <%= link_to 'Edit', edit_post_path(post), :class => 'underline' %>
        <% end %>

        <% if @is_admin || @member_id == post.member_id %>
          <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'underline' %>
        <% end %>
      </div>
    <br>
    <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>

    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>
    

app/views/posts/show.html.erb
<div class='wrapper'>
  <%= render(:partial => 'navbar', :locals => {:is_logged_in => true}) %>
  <div class='container'>
    <p id="notice"><%= notice %></p>

    <div class='box'>
      <p>
        <strong>By:</strong>
        <% @user = Member.find(@post.member_id) %>
        <%= @user.name %>
      </p>

      <p>
        <strong>Title:</strong>
        <%= @post.title %>
      </p>
      <p>
        <strong>Body:</strong>
        <%= @post.body %>
      </p>

      <p>
        <strong>Likes:</strong>
        <%= @post.numlikes %>
      </p>
      <p>
        <strong>Liked by:</strong>
      </p>

      <% @likes = Like.where(post_id: @post.id) %>
      <% if (@likes != nil) %>
        <% @likes.each do |like| %>
          <% @member = Member.find(like.member_id) %>
          <p><%= @member.name %></p>
        <% end %>
      <% end %>

      <% @member_id = Member.where(uid: current_admin.uid).first().id %>

      <% if @member_id == @post.member_id %>
        <%= link_to 'Edit', edit_post_path(@post), :class => 'underline' %> |
      <% end %>
      <%= link_to 'Back', posts_path, :class => 'underline' %> |


      <% if(Like.exists?(:member_id => @member_id, :post_id => @post.id)) %>
        <% @like = Like.find_by(member_id: @member_id, post_id: @post.id) %>
        <%= link_to("Un-like", delete_like_path(@like, :post_id => @post.id, :member_id => @member_id), data: { confirm: 'Are you sure?' }, :class => 'underline') %>
      <% else %>
        <%= link_to("Like", likes_path(:like => @like, :post_id => @post.id, :member_id => @member_id), method: :create, :class => 'underline') %>
      <% end %>
    </div>


  </div>
</div>